name: strongheart
favicon: null
layout_spectrum: 0.99818
typography_spectrum: 0.8155186485964805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4693ff'
    - '#4bc4ff'
    - '#ff9e2b'
    - '#fff0b7'
    - '#ea6e2e'
  brandStrength: 0.25
  lightness: 0.4338594884611666
  saturation: 0.5853009093552828
  rhythmicContrast: 0.017611326184123755
purpose: []
