name: strongheart
favicon: null
layout_spectrum: 0.7322104887571186
typography_spectrum: 0.8155186485964805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1f1f'
    - '#bb884f'
    - '#fcae88'
    - '#7b5834'
  brandStrength: 0.5625
  lightness: 0.4338594884611666
  saturation: 0.5853009093552828
  rhythmicContrast: 0.017611326184123755
purpose: []
