name: strongheart
favicon: null
layout_spectrum: 0.7322104887571186
typography_spectrum: 0.8155186485964805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffe3'
    - '#fe845b'
    - '#dd0071'
    - '#0098dc'
    - '#2b24a6'
  brandStrength: 0.7742776703089476
  lightness: 0.4338594884611666
  saturation: 0.5853009093552828
  rhythmicContrast: 0.017611326184123755
purpose: []
